package DAO.mapper;


import DAO.entity.Channel;

import java.util.List;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    int deleteByPrimaryKey(Integer channleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    Channel selectByPrimaryKey(Integer channleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    List<Channel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    int updateByPrimaryKey(Channel record);
}