package DAO.mapper;


import DAO.entity.Htmls;

import java.util.List;

public interface HtmlsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htmls
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    int deleteByPrimaryKey(Integer channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htmls
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    int insert(Htmls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htmls
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    Htmls selectByPrimaryKey(Integer channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htmls
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    List<Htmls> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htmls
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    int updateByPrimaryKey(Htmls record);

    Htmls selectByUrl(String url);

    List<Htmls> selectByChannelId(Integer channleId);

}