package DAO.entity;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channle_Id
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    private Integer channleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.seed_url
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    private String seedUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_name
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.regex
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    private String regex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channle_Id
     *
     * @return the value of channel.channle_Id
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public Integer getChannleId() {
        return channleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channle_Id
     *
     * @param channleId the value for channel.channle_Id
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public void setChannleId(Integer channleId) {
        this.channleId = channleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.seed_url
     *
     * @return the value of channel.seed_url
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public String getSeedUrl() {
        return seedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.seed_url
     *
     * @param seedUrl the value for channel.seed_url
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public void setSeedUrl(String seedUrl) {
        this.seedUrl = seedUrl == null ? null : seedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_name
     *
     * @return the value of channel.channel_name
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_name
     *
     * @param channelName the value for channel.channel_name
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.regex
     *
     * @return the value of channel.regex
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public String getRegex() {
        return regex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.regex
     *
     * @param regex the value for channel.regex
     *
     * @mbggenerated Thu May 18 08:47:33 CST 2017
     */
    public void setRegex(String regex) {
        this.regex = regex == null ? null : regex.trim();
    }
}