package DAO.entity;

public class Cluster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUSTER.id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUSTER.cluster_id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    private String clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUSTER.url
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUSTER.id
     *
     * @return the value of CLUSTER.id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUSTER.id
     *
     * @param id the value for CLUSTER.id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUSTER.cluster_id
     *
     * @return the value of CLUSTER.cluster_id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public String getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUSTER.cluster_id
     *
     * @param clusterId the value for CLUSTER.cluster_id
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public void setClusterId(String clusterId) {
        this.clusterId = clusterId == null ? null : clusterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUSTER.url
     *
     * @return the value of CLUSTER.url
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUSTER.url
     *
     * @param url the value for CLUSTER.url
     *
     * @mbggenerated Thu May 18 10:00:35 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}