package DAO.entity;

public class Htmls {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htmls.channel_id
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htmls.url
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htmls.content
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htmls.processContent
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    private String processcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htmls.channel_id
     *
     * @return the value of htmls.channel_id
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htmls.channel_id
     *
     * @param channelId the value for htmls.channel_id
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htmls.url
     *
     * @return the value of htmls.url
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htmls.url
     *
     * @param url the value for htmls.url
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htmls.content
     *
     * @return the value of htmls.content
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htmls.content
     *
     * @param content the value for htmls.content
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htmls.processContent
     *
     * @return the value of htmls.processContent
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public String getProcesscontent() {
        return processcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htmls.processContent
     *
     * @param processcontent the value for htmls.processContent
     *
     * @mbggenerated Thu May 18 08:56:43 CST 2017
     */
    public void setProcesscontent(String processcontent) {
        this.processcontent = processcontent == null ? null : processcontent.trim();
    }
}